### basic playbook to delete some SVI's no longer needed on COS00/01 core switches
---

- name: run arbitary command
  hosts: all
  connection: local
  gather_facts: no
 
  tasks:
  - name: delete SVI's from a pair of nexus core switches
    cisco.nxos.nxos_command:
      commands:
      - configure terminal
      - command: no interface vlan901
      - command: no interface vlan902
      - command: no interface vlan903
      - command: no interface vlan904
      - command: no interface vlan905
      - command: no interface vlan906
      - command: no interface vlan907
      - command: no interface vlan908
      - command: no interface vlan909
      - command: no interface vlan911
      - command: no interface vlan912
      - command: no interface vlan913
      - command: no interface vlan914
      - command: no interface vlan915
      - command: no interface vlan916
      - command: no interface vlan920
      - command: no interface vlan1008
      - command: no interface vlan1010
      - command: no interface vlan1014
      - command: no interface vlan1111
      - command: no interface vlan1112
      - command: no interface vlan1113
      - command: no interface vlan1114
      - command: no interface vlan1115
      - command: no interface vlan1116
      - command: no interface vlan1117
      - command: no interface vlan1118
      - command: no interface vlan1119
      - command: no interface vlan1120
      - command: no interface vlan1124
      - command: no interface vlan1129
      - command: no interface vlan1130
      - command: no interface vlan1131
      - command: no interface vlan1132
      - command: no interface vlan1133
      - command: no interface vlan1135
      - command: no interface vlan2000
      - command: no interface vlan2006
      - command: no interface vlan2026
      - command: no interface vlan2027
      - command: no interface vlan2028
      - command: no interface vlan2029
    register: command_output

  - name: CYA save the configuration!!
    nxos_command:
      commands: copy running-config startup-config
