### Cisco NX-API vulnerability audit
### basic playbook to audit the feature status of NX-API across all our nexus switches

### HOW TO USE: run the play against the brookwood.ini or slc inventory file with "-l switch" and limit the run to the devices that are NX-OS

### all the core switch inventory
  ### ansible-playbook cisco_nx-api_audit.yml -i inventory/splat.ini
  

---

- name: audit nx-api status
  hosts: all
  connection: local
  gather_facts: no
 
  tasks:
  - name: show feature | include nxapi
    cisco.nxos.nxos_command:
      commands:
      - show feature | include nxapi      
    register: command_output

  - name: "Task 2: Display stdout_lines[0]"
    debug: 
      msg:  "{{ command_output.stdout_lines }}"
