### playbook to automate adding new vlans to an existing trunk interfaces
### To run the playbook with a specific seed file:
### ansible-playbook cisco_switchport_trunk.yml -i inventory/Cisco/blah/blah -e "include_vars=torx-y.yml"

---
- name: modify switchport trunk allowed vlans
  hosts: all
  connection: local
  gather_facts: no
    
  tasks:
    - name: include_vars
      include_vars: "{{ include_vars }}"

    - name: task1 - add new vlans to existing trunk interface
      cisco.nxos.nxos_l2_interface:
        name: "{{ item.key }}"
        mode: "{{ item.value.mode }}"
        trunk_allowed_vlans: "{{ item.value.trunk_allowed_vlans }}"
      loop: "{{ trunk_int | dict2items }}"

    - name: CYA save the configuration!!
      nxos_command:
          commands: copy running-config startup-config
