### playbook to make it easy to run a single playthat saves the config on a group of devices
### ansible-playbook cisco_save_config.yml -i inventory/Cisco/blah/blah 

---
- name: save the config you dumbass!
  hosts: all
  connection: local
  gather_facts: no
    
  tasks:
    - name: CYA save the configuration!!
      nxos_command:
          commands: copy running-config startup-config
