### working playbook to issue 'show ver' on cisco IOS devices
---

- hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: "Task 1 - issue show version on remote device"
      cisco.ios.ios_command:
        commands:
        - show version
      register: command_output
     
    - name: "Task 2: Display stdout_lines[0]"
      debug: 
        msg:  "{{ command_output.stdout_lines }}"

  