---

- hosts: all
  gather_facts: false
  connection: network_cli

  # vars:
  #   ansible_user: paul.dinapoli@nweacolo.pvt
  #   ansible_become: yes
  #   ansible_become_method: enable
  #   host_key_checking: false
  #   ansible_network_os: ios
 
  tasks:
    - name: testing enable mode commands
      cisco.ios.ios_command:
        commands:
        - show run
      register: command_output
     
    - name: "Task 2: Display stdout_lines[0]"
      debug: 
        msg:  "{{ command_output.stdout_lines }}"

    