### Cisco NX-OS BFD feature vulnerability audit
### basic playbook to audit the feature status of BFD (bidirectional forwarding detection) across all our core switches

### HOW TO USE: run the play against the inventory file with "-l switch" and limit the run to specific switches

---

- name: audit NX-OS BFD feature status
  hosts: all
  connection: local
  gather_facts: no
 
  tasks:
  - name: show feature | include bfd
    cisco.nxos.nxos_command:
      commands:
      - show feature | include bfd    
    register: command_output

  - name: "Task 2: Display stdout_lines[0]"
    debug: 
      msg:  "{{ command_output.stdout_lines }}"
