### intent of this playbook is to collapse and standardize our vlan.dat configuration
### across the entire COR and TOR fleet - so that a single playbook will deploy the same vlan
### list across all switches within each colo.  


### how to use: 
  ### ansible-playbook cisco_vlan.dat_standardized_site.yml -i inventory/Cisco/inventory_here -l "specify-scope-here" -k

---

- name: standardize vlans across all switches
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  
    - name: create one big giant vlan.dat
      cisco.nxos.nxos_vlan:
        aggregate:
        - {vlan_id: 2, name: f5_HA}
        - {vlan_id: 4, name: PAN_HA2}
        - {vlan_id: 10, name: vMotion_172.17.1.0/24 }
        - {vlan_id: 40, name: POD1a_172.18.4.x/24 }
        - {vlan_id: 50, name: POD1b_172.18.5.x/24 }
        - {vlan_id: 60, name: POD4a_172.17.6.0/24_dbc_iscsi_A}
        - {vlan_id: 80, name: POD1-4a_172.17.8.x/24 }
        - {vlan_id: 98, name: new_10gig_wan}
        - {vlan_id: 99, name: new_rubrik_archiving}
        - {vlan_id: 100, name: POD3a_172.17.10.0/24 }
        - {vlan_id: 110, name: POD3b_172.17.11.0/24 }
        - {vlan_id: 172, name: mgmt}
        - {vlan_id: 333, name: MAP2-PAN-10.211.0.0/29}
        - {vlan_id: 444, name: WAN-10.211.0.8/29}
        - {vlan_id: 600, name: FW_INSIDE}
        - {vlan_id: 800, name: PII_10.208.0.0/24 }
        - {vlan_id: 901, name: team01_10.209.1.x/24 }
        - {vlan_id: 902, name: team02_10.209.2.x/24 }
        - {vlan_id: 903, name: team03-10.209.3.0/24 }
        - {vlan_id: 904, name: team04_10.209.4.x/24 }
        - {vlan_id: 905, name: team05-10.209.5.0/24 }
        - {vlan_id: 906, name: team06_10.209.6.x/24 }
        - {vlan_id: 907, name: team07-10.209.7.0/24 }
        - {vlan_id: 908, name: team08-10.209.8.0/24 }
        - {vlan_id: 909, name: team09_10.209.9.x/24 }
        - {vlan_id: 910, name: ext01_10.209.10.x/24 }
        - {vlan_id: 911, name: team11-10.209.11.0/24 }
        - {vlan_id: 912, name: team12-10.209.12.0/24 }
        - {vlan_id: 913, name: team13-10.209.13.0/24 }
        - {vlan_id: 914, name: team14-10.209.14.0/24 }
        - {vlan_id: 915, name: team15-10.209.15.0/24 }
        - {vlan_id: 916, name: team10_10.209.16.x/24 }
        - {vlan_id: 917, name: SE-10.209.17.0/24 }
        - {vlan_id: 918, name: int03_new-10.209.18.0/24 }
        - {vlan_id: 919, name: ORF_dev_hosts_10.209.19.0/24 }
        - {vlan_id: 920, name: team16_VM's_10.209.20.0/24 }
        - {vlan_id: 921, name: Dev-QA_hosts_10.209.21.0/24}
        - {vlan_id: 922, name: stp-vm's-10.209.22.0/24}
        - {vlan_id: 923, name: dvp01-vm's-10.209.23.0/24}
        - {vlan_id: 924, name: prp-vm's-10.209.24.0/24}
        - {vlan_id: 925, name: qap01-vm's-10.209.25.0/24}
        - {vlan_id: 998, name: null}
        - {vlan_id: 999, name: native}
        - {vlan_id: 1000, name: public}
        - {vlan_id: 1001, name: f5-asa}
        - {vlan_id: 1002, name: RD1_transit_198.18.1.0/24}
        - {vlan_id: 1003, name: RD0_transit_198.18.2.0/24}
        - {vlan_id: 1008, name: PXE_10.210.8.0/24}
        - {vlan_id: 1009, name: IPMI_10.210.9.0/24}
        - {vlan_id: 1010, name: netmgmt-10.210.10.0/24}
        - {vlan_id: 1011, name: jumpboxes-10.210.11.0/24}
        - {vlan_id: 1012, name: ESX-Management-10.210.12.0/24}
        - {vlan_id: 1013, name: INF-Mgmt-10.213.13.0/24}
        - {vlan_id: 1014, name: InfoSec-Mgmt-Vlan-10.210.14.0/24}
        - {vlan_id: 1015, name: ext01-RD0-VIPS-10.210.15.0/24}
        - {vlan_id: 1016, name: devops-tools-10.210.16.0/24}
        - {vlan_id: 1017, name: db-management-10.210.17.0/24}
        - {vlan_id: 1018, name: CICD-10.210.18.0/24}
        - {vlan_id: 1019, name: Infra_Tools-10.210.19.0/24}
        - {vlan_id: 1020, name: Test-10.210.20.0/24}
        - {vlan_id: 1111, name: team01-10.211.11.0/24}
        - {vlan_id: 1112, name: team02-10.211.12.0/24}
        - {vlan_id: 1113, name: team03-10.211.13.0/24}
        - {vlan_id: 1114, name: team04-10.211.14.0/24}
        - {vlan_id: 1115, name: team05-10.211.15.0/24}
        - {vlan_id: 1116, name: team06-10.211.16.0/24}
        - {vlan_id: 1117, name: team07-10.211.17.0/24}
        - {vlan_id: 1118, name: team08-10.211.18.0/24}
        - {vlan_id: 1119, name: team09-10.211.19.0/24}
        - {vlan_id: 1120, name: team10-10.211.20.0/24}
        - {vlan_id: 1121, name: beta01-10.211.21.0/24}
        - {vlan_id: 1122, name: cqc01-10.211.22.0/24}
        - {vlan_id: 1123, name: int03-10.211.23.0/24}
        - {vlan_id: 1124, name: mgmt-10.211.24.0/24}
        - {vlan_id: 1125, name: prd-10.211.25.0/24}
        - {vlan_id: 1126, name: se-10.211.26.0/24}
        - {vlan_id: 1127, name: stg01-10.211.27.0/24}
        - {vlan_id: 1128, name: sus01-10.211.28.0/24}
        - {vlan_id: 1129, name: f5-team11-10.211.29.0/24}
        - {vlan_id: 1130, name: f5-team12-10.211.30.0/24}
        - {vlan_id: 1131, name: f5-team13-10.211.31.0/24}
        - {vlan_id: 1132, name: f5-team14-10.211.32.0/24}
        - {vlan_id: 1133, name: f5-team15-10.211.33.0/24}
        - {vlan_id: 1134, name: ORF_dev_RD0_vips_10.211.34.0/24}
        - {vlan_id: 1135, name: team16_VIPS_10.211.35.0/24}
        - {vlan_id: 1136, name: stp-vips-10.211.36.0/24}
        - {vlan_id: 1137, name: dvp01-vips-10.211.37.0/24}
        - {vlan_id: 1138, name: prp-vips-10.211.38.0/24}
        - {vlan_id: 1139, name: qap01-vips-10.211.39.0/24}
        - {vlan_id: 1140, name: team_cicd_vm's_10.211.40.0/24}
        - {vlan_id: 1141, name: team_cicd_vips_10.211.41.0/24}
        - {vlan_id: 2000, name: Infrastructure}
        - {vlan_id: 2001, name: sus01}
        - {vlan_id: 2002, name: stg01}
        - {vlan_id: 2003, name: Int03}
        - {vlan_id: 2004, name: STG}
        - {vlan_id: 2005, name: int01}
        - {vlan_id: 2006, name: shared-prod}
        - {vlan_id: 2007, name: internal-vips}
        - {vlan_id: 2008, name: int02}
        - {vlan_id: 2009, name: iscsi}
        - {vlan_id: 2010, name: vm-db-testing}
        - {vlan_id: 2011, name: cqc}
        - {vlan_id: 2012, name: vmotion}
        - {vlan_id: 2013, name: nfs-vlan_id}
        - {vlan_id: 2014, name: cicd-1}
        - {vlan_id: 2015, name: pit-slc-netapp-replication}
        - {vlan_id: 2016, name: reliability}
        - {vlan_id: 2017, name: team-03}
        - {vlan_id: 2018, name: mpls}
        - {vlan_id: 2019, name: petras}
        - {vlan_id: 2020, name: slc-ptp}
        - {vlan_id: 2022, name: team-04}
        - {vlan_id: 2023, name: team-05}
        - {vlan_id: 2024, name: team-06}
        - {vlan_id: 2026, name: team-07}
        - {vlan_id: 2027, name: team-08}
        - {vlan_id: 2028, name: team-09}
        - {vlan_id: 2029, name: team-10}
        - {vlan_id: 2030, name: kubernetes}
        - {vlan_id: 3000, name: dmz-vips_10.123.40.0/24}
        - {vlan_id: 3001, name: dmz-nodes_10.211.20.0/22}

    - name: CYA save the configuration!!
      nxos_command:
        commands: copy running-config startup-config


