- hosts: '{{ target | default("lab") }}'
  connection: local

  collections:
    - paloaltonetworks.panos
  
  tasks:
  - name: create DMZ zone on a firewall
    panos_zone:
      provider: '{{ provider }}'
      zone: 'dmz'
      mode: 'layer3'
  
  - name: ethernet1/3 as static in zone dmz
    panos_interface:
      provider: '{{ provider }}'
      if_name: "ethernet1/3"
      mode: "layer3"
      ip: ["10.1.1.1/24"]
      enable_dhcp: false
      zone_name: "dmz"
